'use client';
import { useMemo,useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowDown,ArrowLeft,ArrowUp,Search,Trash2 } from 'lucide-react';
import { saveCollection,saveCollectionProducts,deleteCollection } from '@/lib/actions/admin-collections';

export default function CollectionEditor({collection,products}:{collection?:any;products:any[]}){
 const router=useRouter(); const existing=(collection?.product_collection_items||[]).sort((a:any,b:any)=>a.order_index-b.order_index).map((x:any)=>x.product_id);
 const [selected,setSelected]=useState<string[]>(existing); const [search,setSearch]=useState(''); const [saving,setSaving]=useState(false);
 const filtered=useMemo(()=>products.filter((p:any)=>p.name?.toLowerCase().includes(search.toLowerCase())),[products,search]);
 const add=(id:string)=>setSelected(x=>x.includes(id)?x:[...x,id]);
 const remove=(id:string)=>setSelected(x=>x.filter(v=>v!==id));
 const move=(id:string,d:number)=>setSelected(x=>{const i=x.indexOf(id),n=i+d;if(i<0||n<0||n>=x.length)return x;const y=[...x];[y[i],y[n]]=[y[n],y[i]];return y});
 const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setSaving(true);const fd=new FormData(e.currentTarget);if(collection?.id)fd.set('id',collection.id);const a=await saveCollection(fd);if(!a.success||!a.id){alert(a.message);setSaving(false);return}const b=await saveCollectionProducts(a.id,selected);setSaving(false);if(!b.success){alert(b.message);return}router.push('/admin/colecciones');router.refresh()};
 return <form onSubmit={submit} className="space-y-6"><button type="button" onClick={()=>router.push('/admin/colecciones')} className="inline-flex items-center gap-2 text-sm font-semibold"><ArrowLeft className="h-4 w-4"/>Colecciones</button><div><h1 className="text-2xl font-bold">{collection?'Editar colección':'Crear colección'}</h1><p className="text-gray-500">Funciona como una colección de Shopify: agregá productos, ordenalos y elegí si se muestra en el Home.</p></div>
 <div className="grid gap-6 lg:grid-cols-[1fr_340px]"><div className="space-y-6"><section className="rounded-xl border bg-white p-5 space-y-4"><h2 className="font-bold">Información</h2><input name="title" required defaultValue={collection?.title||''} placeholder="Nombre de la colección" className="w-full rounded-lg border p-3"/><input name="slug" required defaultValue={collection?.slug||''} placeholder="slug-de-la-coleccion" className="w-full rounded-lg border p-3"/><textarea name="description" defaultValue={collection?.description||''} placeholder="Descripción" className="min-h-24 w-full rounded-lg border p-3"/></section>
 <section className="rounded-xl border bg-white p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold">Productos</h2><p className="text-sm text-gray-500">Orden predeterminado: <strong>Manualmente</strong></p></div><span className="text-sm">{selected.length} productos</span></div><div className="space-y-2">{selected.map((id,i)=>{const p=products.find((x:any)=>x.id===id);if(!p)return null;return <div key={id} className="flex items-center gap-3 rounded-lg border p-3"><span className="w-7 text-center font-bold">{i+1}</span><span className="min-w-0 flex-1 truncate font-medium">{p.name}</span><button type="button" onClick={()=>move(id,-1)} disabled={i===0}><ArrowUp className="h-4 w-4"/></button><button type="button" onClick={()=>move(id,1)} disabled={i===selected.length-1}><ArrowDown className="h-4 w-4"/></button><button type="button" onClick={()=>remove(id)}><Trash2 className="h-4 w-4 text-red-500"/></button></div>})}</div><div className="mt-5 border-t pt-5"><div className="relative mb-3"><Search className="absolute left-3 top-3 h-4 w-4 text-gray-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar productos para agregar..." className="w-full rounded-lg border py-2.5 pl-9 pr-3"/></div><div className="max-h-72 overflow-auto rounded-lg border">{filtered.filter((p:any)=>!selected.includes(p.id)).map((p:any)=><button key={p.id} type="button" onClick={()=>add(p.id)} className="flex w-full items-center justify-between border-b p-3 text-left last:border-0 hover:bg-gray-50"><span>{p.name}</span><span className="text-sm font-semibold text-corpicia-green">Agregar</span></button>)}</div></div></section></div>
 <aside className="space-y-5"><section className="rounded-xl border bg-white p-5 space-y-4"><h2 className="font-bold">Disponibilidad</h2><label className="flex gap-2"><input type="checkbox" name="is_active" value="true" defaultChecked={collection?collection.is_active:true}/>Colección activa</label><label className="flex gap-2"><input type="checkbox" name="show_on_home" value="true" defaultChecked={collection?.show_on_home||false}/>Mostrar en la Home</label><label className="block text-sm font-medium">Ubicación en la Home<input name="home_order_index" type="number" min="1" defaultValue={collection?.home_order_index||''} placeholder="1" className="mt-1 w-full rounded-lg border p-2.5"/></label><label className="block text-sm font-medium">Orden de productos<select name="sort_mode" defaultValue={collection?.sort_mode||'manual'} className="mt-1 w-full rounded-lg border p-2.5"><option value="manual">Manualmente</option><option value="title_asc">Título A–Z</option><option value="title_desc">Título Z–A</option><option value="price_asc">Precio menor a mayor</option><option value="price_desc">Precio mayor a menor</option><option value="newest">Más nuevos</option><option value="oldest">Más antiguos</option></select></label></section><button disabled={saving} className="w-full rounded-lg bg-corpicia-green p-3 font-bold text-white">{saving?'Guardando...':'Guardar colección'}</button>{collection&&<button type="button" onClick={async()=>{if(confirm('¿Eliminar esta colección?')){await deleteCollection(collection.id);router.push('/admin/colecciones');router.refresh()}}} className="w-full rounded-lg border border-red-200 p-3 font-semibold text-red-600">Eliminar colección</button>}</aside></div></form>
}