'use client';

import { useState, useTransition } from 'react';
import Image from 'next/image';
import { ImagePlus, Loader2, Plus, Save, Trash2, ArrowUp, ArrowDown, Star } from 'lucide-react';
import { saveWorkGallerySettings, uploadWorkGalleryImage } from '@/lib/actions/admin-work-gallery';
import { normalizeWorkGalleryPhotos, type WorkGalleryItem, type WorkGalleryPhoto, type WorkGallerySettings, type WorkPhotoStage } from '@/lib/repositories/work-gallery';

const stages: Array<{ value: WorkPhotoStage; label: string }> = [{ value:'before',label:'ANTES' },{ value:'process',label:'PROCESO' },{ value:'after',label:'DESPUÉS' }];

export function WorkGalleryEditor({ initial }: { initial: WorkGallerySettings }) {
  const [settings,setSettings]=useState<WorkGallerySettings>(()=>({...initial,items:initial.items.map(i=>({...i,images:normalizeWorkGalleryPhotos(i)}))}));
  const [message,setMessage]=useState(''); const [pending,startTransition]=useTransition();
  const updateItem=(id:string,patch:Partial<WorkGalleryItem>)=>setSettings(s=>({...s,items:s.items.map(i=>i.id===id?{...i,...patch}:i)}));
  const add=()=>setSettings(s=>({...s,items:[...s.items,{id:crypto.randomUUID(),title:'',category:'Paisajismo',location:'',description:'',image:'',images:[],active:true}]}));
  const remove=(id:string)=>setSettings(s=>({...s,items:s.items.filter(i=>i.id!==id)}));
  const move=(index:number,direction:-1|1)=>setSettings(s=>{const items=[...s.items];const next=index+direction;if(next<0||next>=items.length)return s;[items[index],items[next]]=[items[next],items[index]];return{...s,items};});
  const photosOf=(item:WorkGalleryItem)=>normalizeWorkGalleryPhotos(item);
  const updatePhotos=(id:string,fn:(photos:WorkGalleryPhoto[])=>WorkGalleryPhoto[])=>setSettings(s=>({...s,items:s.items.map(i=>{if(i.id!==id)return i;const images=fn(photosOf(i)).map((p,n)=>({...p,order:n}));return{...i,images,image:images.some(p=>p.url===i.image)?i.image:(images.find(p=>p.stage==='after')?.url||images[0]?.url||'')};})}));
  const uploadFiles=async(id:string,files?:FileList|null)=>{if(!files?.length)return;setMessage(`Subiendo ${files.length} foto(s)...`);const added:WorkGalleryPhoto[]=[];for(const file of Array.from(files)){const fd=new FormData();fd.append('file',file);const result=await uploadWorkGalleryImage(fd);if(!result.success||!result.publicUrl){setMessage(result.error||'Error al subir una imagen.');return;}added.push({id:crypto.randomUUID(),url:result.publicUrl,stage:'process',order:0});}updatePhotos(id,p=>[...p,...added].slice(0,20));setMessage(`${added.length} foto(s) cargada(s). Marcá cada una como Antes, Proceso o Después y guardá.`);};
  const removePhoto=(id:string,photoId:string)=>updatePhotos(id,p=>p.filter(x=>x.id!==photoId));
  const setStage=(id:string,photoId:string,stage:WorkPhotoStage)=>updatePhotos(id,p=>p.map(x=>x.id===photoId?{...x,stage}:x));
  const movePhoto=(id:string,photoId:string,direction:-1|1)=>updatePhotos(id,p=>{const index=p.findIndex(x=>x.id===photoId);const target=index+direction;if(index<0||target<0||target>=p.length)return p;const copy=[...p];[copy[index],copy[target]]=[copy[target],copy[index]];return copy;});
  const setCover=(id:string,url:string)=>updateItem(id,{image:url});
  const save=()=>startTransition(async()=>{setMessage('Guardando...');const result=await saveWorkGallerySettings(settings);setMessage(result.success?'Trabajos guardados correctamente.':result.error||'No se pudo guardar.');});

  return <div className="mx-auto max-w-[1280px] space-y-6 pb-12">
    <div className="flex flex-col gap-4 rounded-2xl border bg-white p-5 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-corpicia-green">Contenido web</p><h1 className="mt-1 text-2xl font-bold">Galería de trabajos</h1><p className="mt-1 text-sm text-gray-500">Creá una obra y ordená sus fotos como ANTES → PROCESO → DESPUÉS.</p></div><button onClick={add} className="inline-flex items-center justify-center gap-2 rounded-xl bg-corpicia-green px-4 py-3 text-sm font-bold text-white"><Plus className="h-4 w-4"/> Nuevo trabajo</button></div>
    <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold">Título de sección<input value={settings.title} onChange={e=>setSettings({...settings,title:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-2.5 font-normal"/></label><label className="text-sm font-semibold">Etiqueta<input value={settings.eyebrow} onChange={e=>setSettings({...settings,eyebrow:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-2.5 font-normal"/></label><label className="md:col-span-2 text-sm font-semibold">Descripción<textarea value={settings.description} onChange={e=>setSettings({...settings,description:e.target.value})} rows={2} className="mt-1 w-full rounded-xl border px-3 py-2.5 font-normal"/></label></div><label className="mt-4 flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={settings.active} onChange={e=>setSettings({...settings,active:e.target.checked})} className="h-4 w-4"/> Publicar trabajos en /proyectos</label></section>
    <div className="space-y-6">{settings.items.map((item,index)=>{const photos=photosOf(item);return <article key={item.id} className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="grid lg:grid-cols-[320px_1fr]"><div className="relative min-h-[240px] bg-gray-100">{item.image?<Image src={item.image} alt={item.title||'Trabajo Corpicia'} fill className="object-cover" sizes="320px"/>:<div className="flex h-full min-h-[240px] items-center justify-center text-gray-400"><ImagePlus className="h-10 w-10"/></div>}<span className="absolute left-3 top-3 rounded-lg bg-black/70 px-2 py-1 text-xs font-bold text-white">Portada del proyecto</span></div><div className="space-y-3 p-4"><div className="grid gap-3 sm:grid-cols-2"><input placeholder="Título del trabajo" value={item.title} onChange={e=>updateItem(item.id,{title:e.target.value})} className="rounded-xl border px-3 py-2.5 font-semibold"/><select value={item.category} onChange={e=>updateItem(item.id,{category:e.target.value})} className="rounded-xl border px-3 py-2.5"><option>Paisajismo</option><option>Césped</option><option>Riego automático</option><option>Mantenimiento</option><option>Otro</option></select></div><input placeholder="Ubicación (opcional)" value={item.location} onChange={e=>updateItem(item.id,{location:e.target.value})} className="w-full rounded-xl border px-3 py-2.5"/><textarea placeholder="Contá brevemente qué trabajo se realizó" value={item.description} onChange={e=>updateItem(item.id,{description:e.target.value})} rows={2} className="w-full rounded-xl border px-3 py-2.5"/><div className="flex items-center justify-between"><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={item.active} onChange={e=>updateItem(item.id,{active:e.target.checked})}/> Activo</label><div className="flex gap-1"><button onClick={()=>move(index,-1)} className="rounded-lg border p-2"><ArrowUp className="h-4 w-4"/></button><button onClick={()=>move(index,1)} className="rounded-lg border p-2"><ArrowDown className="h-4 w-4"/></button><button onClick={()=>remove(item.id)} className="rounded-lg border border-red-200 p-2 text-red-600"><Trash2 className="h-4 w-4"/></button></div></div></div></div>
      <div className="border-t p-4"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><p className="font-bold">Secuencia de la obra ({photos.length}/20)</p><p className="text-xs text-gray-500">Cada foto debe indicar en qué momento del trabajo fue tomada.</p></div><label className="cursor-pointer rounded-lg bg-corpicia-green px-3 py-2 text-xs font-bold text-white"><Plus className="mr-1 inline h-3.5 w-3.5"/> Agregar fotos<input type="file" multiple accept="image/jpeg,image/png,image/webp" className="hidden" onChange={e=>uploadFiles(item.id,e.target.files)}/></label></div>
      {photos.length?<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{photos.map((photo,photoIndex)=><div key={photo.id} className="overflow-hidden rounded-xl border bg-gray-50"><div className="relative aspect-[4/3]"><Image src={photo.url} alt="Foto del trabajo" fill className="object-cover" sizes="260px"/><span className="absolute left-2 top-2 rounded-md bg-black/70 px-2 py-1 text-[10px] font-bold text-white">#{photoIndex+1}</span>{item.image===photo.url&&<span className="absolute right-2 top-2 rounded-md bg-green-700 px-2 py-1 text-[10px] font-bold text-white">PORTADA</span>}</div><div className="space-y-2 p-2"><div className="grid grid-cols-3 gap-1">{stages.map(s=><button key={s.value} type="button" onClick={()=>setStage(item.id,photo.id,s.value)} className={`rounded-md px-1 py-2 text-[10px] font-bold ${photo.stage===s.value?'bg-corpicia-green text-white':'border bg-white text-gray-600'}`}>{s.label}</button>)}</div><div className="flex justify-between"><div className="flex gap-1"><button type="button" onClick={()=>movePhoto(item.id,photo.id,-1)} className="rounded border bg-white p-1.5" title="Mover antes"><ArrowUp className="h-3.5 w-3.5"/></button><button type="button" onClick={()=>movePhoto(item.id,photo.id,1)} className="rounded border bg-white p-1.5" title="Mover después"><ArrowDown className="h-3.5 w-3.5"/></button></div><div className="flex gap-1"><button type="button" onClick={()=>setCover(item.id,photo.url)} className="rounded border bg-white p-1.5 text-green-700" title="Usar como portada"><Star className="h-3.5 w-3.5"/></button><button type="button" onClick={()=>removePhoto(item.id,photo.id)} className="rounded border bg-white p-1.5 text-red-600" title="Eliminar"><Trash2 className="h-3.5 w-3.5"/></button></div></div></div></div>)}</div>:<label className="flex cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed p-8 text-gray-500"><ImagePlus className="mb-2 h-8 w-8"/><span className="text-sm font-bold">Cargar fotos de esta obra</span><span className="text-xs">Después vas a marcar Antes, Proceso o Después.</span><input type="file" multiple accept="image/jpeg,image/png,image/webp" className="hidden" onChange={e=>uploadFiles(item.id,e.target.files)}/></label>}</div>
    </article>})}</div>
    {settings.items.length===0&&<div className="rounded-2xl border border-dashed bg-white p-10 text-center"><ImagePlus className="mx-auto h-10 w-10 text-gray-300"/><p className="mt-3 font-bold">Todavía no hay trabajos cargados</p><p className="mt-1 text-sm text-gray-500">Presioná “Nuevo trabajo” para crear la primera obra.</p></div>}
    <div className="sticky bottom-4 flex items-center justify-between gap-3 rounded-2xl border bg-white/95 p-4 shadow-lg backdrop-blur"><p className="text-sm text-gray-600">{message}</p><button disabled={pending} onClick={save} className="inline-flex items-center gap-2 rounded-xl bg-corpicia-green px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{pending?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>} Guardar cambios</button></div>
  </div>;
}
