'use client';

import { useState, useTransition } from 'react';
import Image from 'next/image';
import { ImagePlus, Loader2, Plus, Save, Trash2, ArrowUp, ArrowDown } from 'lucide-react';
import { saveWorkGallerySettings, uploadWorkGalleryImage } from '@/lib/actions/admin-work-gallery';
import type { WorkGalleryItem, WorkGallerySettings } from '@/lib/repositories/work-gallery';

export function WorkGalleryEditor({ initial }: { initial: WorkGallerySettings }) {
  const [settings, setSettings] = useState(initial);
  const [message, setMessage] = useState('');
  const [pending, startTransition] = useTransition();
  const updateItem = (id: string, patch: Partial<WorkGalleryItem>) => setSettings(s => ({ ...s, items: s.items.map(i => i.id === id ? { ...i, ...patch } : i) }));
  const add = () => setSettings(s => ({ ...s, items: [...s.items, { id: crypto.randomUUID(), title: '', category: 'Paisajismo', location: '', description: '', image: '', active: true }] }));
  const remove = (id: string) => setSettings(s => ({ ...s, items: s.items.filter(i => i.id !== id) }));
  const move = (index: number, direction: -1 | 1) => setSettings(s => { const items = [...s.items]; const next = index + direction; if (next < 0 || next >= items.length) return s; [items[index], items[next]] = [items[next], items[index]]; return { ...s, items }; });
  const upload = async (id: string, file?: File) => { if (!file) return; setMessage('Subiendo imagen...'); const fd = new FormData(); fd.append('file', file); const result = await uploadWorkGalleryImage(fd); if (result.success && result.publicUrl) { updateItem(id, { image: result.publicUrl }); setMessage('Imagen cargada. Guardá los cambios.'); } else setMessage(result.error || 'Error al subir.'); };
  const save = () => startTransition(async () => { setMessage('Guardando...'); const result = await saveWorkGallerySettings(settings); setMessage(result.success ? 'Galería guardada correctamente.' : result.error || 'No se pudo guardar.'); });

  return <div className="mx-auto max-w-[1280px] space-y-6 pb-12">
    <div className="flex flex-col gap-4 rounded-2xl border bg-white p-5 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-corpicia-green">Contenido web</p><h1 className="mt-1 text-2xl font-bold">Galería de trabajos</h1><p className="mt-1 text-sm text-gray-500">Cargá trabajos reales de Corpicia y elegí cuáles aparecen en la web.</p></div><button onClick={add} className="inline-flex items-center justify-center gap-2 rounded-xl bg-corpicia-green px-4 py-3 text-sm font-bold text-white"><Plus className="h-4 w-4"/> Nuevo trabajo</button></div>
    <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold">Título de sección<input value={settings.title} onChange={e=>setSettings({...settings,title:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-2.5 font-normal"/></label><label className="text-sm font-semibold">Etiqueta<input value={settings.eyebrow} onChange={e=>setSettings({...settings,eyebrow:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-2.5 font-normal"/></label><label className="md:col-span-2 text-sm font-semibold">Descripción<textarea value={settings.description} onChange={e=>setSettings({...settings,description:e.target.value})} rows={2} className="mt-1 w-full rounded-xl border px-3 py-2.5 font-normal"/></label></div><label className="mt-4 flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={settings.active} onChange={e=>setSettings({...settings,active:e.target.checked})} className="h-4 w-4"/> Mostrar esta sección en la web</label></section>
    <div className="grid gap-4 lg:grid-cols-2">{settings.items.map((item,index)=><article key={item.id} className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="relative aspect-[16/10] bg-gray-100">{item.image?<Image src={item.image} alt={item.title||'Trabajo Corpicia'} fill className="object-cover" sizes="(max-width:1024px) 100vw,50vw"/>:<div className="flex h-full items-center justify-center text-gray-400"><ImagePlus className="h-10 w-10"/></div>}<label className="absolute bottom-3 right-3 cursor-pointer rounded-lg bg-white px-3 py-2 text-xs font-bold shadow">Cambiar foto<input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={e=>upload(item.id,e.target.files?.[0])}/></label></div><div className="space-y-3 p-4"><div className="grid gap-3 sm:grid-cols-2"><input placeholder="Título del trabajo" value={item.title} onChange={e=>updateItem(item.id,{title:e.target.value})} className="rounded-xl border px-3 py-2.5 font-semibold"/><select value={item.category} onChange={e=>updateItem(item.id,{category:e.target.value})} className="rounded-xl border px-3 py-2.5"><option>Paisajismo</option><option>Césped</option><option>Riego automático</option><option>Mantenimiento</option><option>Otro</option></select></div><input placeholder="Ubicación (opcional)" value={item.location} onChange={e=>updateItem(item.id,{location:e.target.value})} className="w-full rounded-xl border px-3 py-2.5"/><textarea placeholder="Descripción corta del trabajo" value={item.description} onChange={e=>updateItem(item.id,{description:e.target.value})} rows={2} className="w-full rounded-xl border px-3 py-2.5"/><div className="flex items-center justify-between gap-2"><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={item.active} onChange={e=>updateItem(item.id,{active:e.target.checked})}/> Activo</label><div className="flex gap-1"><button onClick={()=>move(index,-1)} className="rounded-lg border p-2" title="Subir"><ArrowUp className="h-4 w-4"/></button><button onClick={()=>move(index,1)} className="rounded-lg border p-2" title="Bajar"><ArrowDown className="h-4 w-4"/></button><button onClick={()=>remove(item.id)} className="rounded-lg border border-red-200 p-2 text-red-600" title="Eliminar"><Trash2 className="h-4 w-4"/></button></div></div></div></article>)}</div>
    {settings.items.length===0&&<div className="rounded-2xl border border-dashed bg-white p-10 text-center"><ImagePlus className="mx-auto h-10 w-10 text-gray-300"/><p className="mt-3 font-bold">Todavía no hay trabajos cargados</p><p className="mt-1 text-sm text-gray-500">Presioná “Nuevo trabajo” para agregar la primera foto.</p></div>}
    <div className="sticky bottom-4 flex items-center justify-between gap-3 rounded-2xl border bg-white/95 p-4 shadow-lg backdrop-blur"><p className="text-sm text-gray-600">{message}</p><button disabled={pending} onClick={save} className="inline-flex items-center gap-2 rounded-xl bg-corpicia-green px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{pending?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>} Guardar cambios</button></div>
  </div>;
}
